version: '3'

services:

  nginx:
    container_name: nginx_dev
    build:
      context: .
      dockerfile: nginx/dev/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    networks:
      - main

  db:
    container_name: db_dev
    image: postgres
    networks: 
      - main
    volumes:
      - pg-data-dev:/var/lib/postgresql/data

  backend:
    container_name: backend_dev
    build: ./backend
    command: /start_dev.sh
    volumes:
      - .:/code
      - django-static:/backend/static
    ports:
      - "8000:8000"
    networks: 
      - main
    depends_on:
      - db

  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/:ro
      - '/app/node_modules'
    ports:
      - "8080:8080"
    networks:
      - main
    depends_on:
      - backend
      - db
    environment:
      - NODE_ENV=development

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - main
  
  celery:
    build: ./backend
    container_name: celery
    command: bash -c 'python3 manage.py watch_celery'
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
    networks:
      - main
  
  flower:
    image: mher/flower
    container_name: flower_dev
    command: flower --url_prefix=flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    networks:
      - main
    depends_on:
      - celery
      - redis
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 9000:9000

networks: 
  main:
    driver: bridge

volumes:
  django-static:
  portainer-data:
  pg-data-dev: