version: '3'

services:

  nginx:
    container_name: nginx_dev
    build:
      context: .
      dockerfile: nginx/dev/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    networks:
      - main

  db:
    container_name: db_dev
    image: postgres
    networks: 
      - main

  backend:
    container_name: backend_dev
    build: ./backend
    command: /start_dev.sh
    volumes:
      - .:/code
      - django-static:/backend/static
    ports:
      - "8000:8000"
    networks: 
      - main
    depends_on:
      - db

  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend:ro
      - '/app/frontend/node_modules'
    ports:
      - "8080:8080"
    networks:
      - main
    depends_on:
      - backend
      - db
    environment:
      - NODE_ENV=development

networks: 
  main:
    driver: bridge

volumes:
  django-static: